### ISSUE TITLE
Is it working on FIFA 20? What do I need to run on Windows?

### ISSUE THREAD

**Issue by Ghelers** [shapecode/fut-api#10]
I have experience in C ++ and C #, but with PHP and WEB I don't know anything.
Is this an application or just a package to run in one?
I need some tips.

**Comment by nicklog** [comment]
Hey, its need a php environment to run. this could be on a windows too, but the performance would be bad. take a look a [xampp](https://www.apachefriends.org/).
Still, it's just a package to run in one application.
