### ISSUE TITLE
How can I get a names of Players in result ? 

### ISSUE THREAD

**Issue by vvvladimir758** [shapecode/fut-api#7]
Hi , the response from  this $fut->search($options) , don't show any literal names data  in result . Where can I get names data, through this API ?

**Comment by nicklog** [comment]
There arent any namens in the results of the ea fut api.

**Comment by vvvladimir758** [comment]
Is there any way to get names of players ?

**Comment by nicklog** [comment]
At the Moment i create a json Rest api with a full fut database. But it's only a Prototype. [futdb.app](https://futdb.app)

**Comment by vvvladimir758** [comment]
Oh that's great, and when you plan to complete this ?
